apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: qbox
spec:
  selector:
    app: qbox
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.frontend.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: qboxapi
spec:
  selector:
    tier: backend
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: qboxdb
spec:
  selector:
    tier: db
  ports:
    - protocol: TCP
      port: 1433
  type: ClusterIP
