version: '3'

services:

  qbox-frontend:
    image: qbox-frontend
    build:
      context: .\QBox.Web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - qbox-backend

  qbox-backend:
    image: qbox-backend
    ports:
      - "81:80"
    build:
      context: .\QBox.Api
      dockerfile: Dockerfile
    depends_on:
      - qbox-db

  qbox-db:
    image: microsoft/mssql-server-windows-developer
    ports:
      - "15785:1433"
    environment:
      sa_password: "1qaz2WSX3edc"
      ACCEPT_EULA: "Y"
