apiVersion: v1
kind: Service
metadata:
  name: qbox-frontend
  labels:
    app: qbox
spec:
  selector:
    app: qbox
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30081
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: qbox-frontend-deployment
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: qbox
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: jakobhub.azurecr.io/qboxweb:2318
        ports:
        - containerPort: 80
      nodeSelector: 
        beta.kubernetes.io/os: windows
   