apiVersion: v1
kind: Service
metadata:
  name: qbox-backend
  labels:
    app: qbox
spec:
  selector:
    app: qbox
    tier: backend
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: qbox-backend-deployment
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: qbox
        tier: backend
    spec:
      containers:
      - name: backend
        image: jakobhub.azurecr.io/qboxapi:2319
        ports:
        - containerPort: 80
      nodeSelector: 
        beta.kubernetes.io/os: windows
   