apiVersion: v1
kind: Service
metadata:
  name: qbox-db
  labels:
    app: qbox
spec:
  selector:
    app: qbox
    tier: db
  ports:
    - protocol: TCP
      port: 1433
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: qbox-db-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: qbox
        tier: db
    spec:
      containers:
      - name: db
        image: microsoft/mssql-server-windows-developer
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          value: "1qaz2WSX3edc"
        - name: ACCEPT_EULA
          value: "Y"
      nodeSelector: 
        beta.kubernetes.io/os: windows
   